### ISSUE TITLE
Log file is not created/written to (EL7)

### ISSUE THREAD

**Issue by jamieburchell** [geerlingguy/ansible-role-memcached#20]
By default, the log file is set to `/var/log/memcached.log` but the file is never created or written to. Even when setting the debug level to `-vvv` the file remains uncreated. I had wondered if this was a permissions issue since the process runs as the `memcached` user and the `/var/log` directory is only writable by `root`, but even after creating the file manually and setting write permission to the `memcached` user, the file remained empty. It seems that the debug information is instead readable in `journalctl`.

**Comment by geerlingguy** [comment]
Yeah... I think with newer OSes using Systemd/Journald, memcache _only_ logs to journald, and not to the log file. The `memcached_log_file` setting seems to only apply to older versions of memcached. It might be good to drop it at some point, or see if there's a way you can tell memcache's config to actually write to the file (or we can just point people to journald docs https://wiki.archlinux.org/index.php/Systemd/Journal)

**Comment by jamieburchell** [comment]
I eventually discovered the same (that it doesn't write to the log file). Happy to have this issue closed.
