### ISSUE TITLE
ubuntu 20.04 memcached service control broken

### ISSUE THREAD

**Issue by ahrib** [geerlingguy/ansible-role-memcached#30]
Ubuntu: 20.04 LTS
role version: 2.2.0

performing any commands via "service" doesnt work correctly on Ubuntu 20.04 LTS

e.g. service memcached stop" doesn't stop the process correctly as output via ps shows the process is still running 
"ps aux |  grep memcache"

**Comment by geerlingguy** [comment]
If you're using Ubuntu, and interacting with the service via the command line, you should use `systemctl` (e.g. `systemctl stop memcached`).

**Comment by ahrib** [comment]
Thanks, you are spot on. 

It is a bug/feature with the Ubuntu package in apt. 

Closing as I certainly don’t expect this role to change this behaviour.
