### ISSUE TITLE
Add support for changing chunk size

### ISSUE THREAD

**Issue by back-2-95** [geerlingguy/ansible-role-memcached#9]
Chunk size is set in OPTIONS with "I":

```
-I 16M
```

So the proposed change would be:

Variable (default size is 1MB = 1M):

```
memcached_chunk_size: 1M
```

And in the template (note, it's I not L):

```
OPTIONS="-I {{ memcached_chunk_size }} -l {{ memcached_listen_ip }} {{ memcached_log_verbosity }} >> {{ memcached_log_file }} 2>&1"
```

**Comment by AndreBaumeier** [comment]
has this been added already?

**Comment by AndreBaumeier** [comment]
forked and created a PR https://github.com/geerlingguy/ansible-role-memcached/pull/19 wondering whether there's a better option to expose even further not yet supported configuration options (without having to fork this role)
